name: xiaozhi
description: "A new Flutter project."

version: 1.0.0+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  bloc: ^9.1.0
  meta: ^1.12.0
  logger: ^2.0.0
  web_socket_channel: ^3.0.2
  record: ^6.0.0
  permission_handler: ^12.0.0+1
  opus_flutter: ^3.0.3
  opus_dart: ^3.0.1
  uuid: ^4.5.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  taudio: ^10.3.0
  sqflite: ^2.4.2
  pull_to_refresh_flutter3: ^2.0.2
  mesh_gradient: ^1.3.8
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/live2d/
    - assets/live2d/Haru/
    - assets/live2d/Haru/expressions/
    - assets/live2d/Haru/motions/
    - assets/live2d/Haru/sounds/
    - assets/live2d/Haru/Haru.2048/
    - assets/live2d/Hiyori/
    - assets/live2d/Mao/
    - assets/live2d/Mark/
    - assets/live2d/Natori/
    - assets/live2d/Rice/
    - assets/live2d/Wanko/

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated